[project]
name = "backend"
version = "0.1.0"
description = "Backend written in FastAPI for our project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.10",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.12",
    "ruff>=0.9.9",
]
